# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 15:26
from __future__ import unicode_literals

import corrfeed.models
import corrfeed.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(editable=False)),
                ('twitter_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('no_of_feeds', models.PositiveIntegerField(default=0)),
                ('resolved', models.PositiveIntegerField(default=0)),
                ('unresolved', models.PositiveIntegerField(default=0)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('dp', models.ImageField(blank=True, upload_to=corrfeed.models.dp_path)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('files', models.FileField(upload_to='files/%Y/%m/%d', validators=[corrfeed.validator.validate_file_extension])),
                ('files2', models.FileField(blank=True, upload_to='files/%Y/%m/%d', validators=[corrfeed.validator.validate_file_extension])),
                ('files3', models.FileField(blank=True, upload_to='files/%Y/%m/%d', validators=[corrfeed.validator.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(max_length=300)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corrfeed.Country')),
                ('following_cats', models.ManyToManyField(blank=True, related_name='following_cats', to='corrfeed.Category')),
                ('following_orgs', models.ManyToManyField(blank=True, related_name='following_orgs', to='corrfeed.Authority')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='archive',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrfeed.Authority'),
        ),
        migrations.AddField(
            model_name='feed',
            name='category_of_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corrfeed.Category'),
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='user_concerns',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='users_experienced',
            field=models.ManyToManyField(blank=True, related_name='experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authority',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corrfeed.Category'),
        ),
        migrations.AddField(
            model_name='authority',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corrfeed.Country'),
        ),
    ]
