# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0002_auto_20160804_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='slug',
            field=models.SlugField(default='default-slug', editable=False),
        ),
    ]
