# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0003_authority_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
