# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0005_auto_20160806_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='twitter_hashtag',
            field=models.TextField(default='@organization'),
        ),
    ]
