# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0006_authority_twitter_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='twitter_hashtag',
            field=models.CharField(default='@organization', max_length=30),
        ),
    ]
