# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0007_auto_20160819_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='twitter_hashtag',
            field=models.CharField(max_length=30),
        ),
    ]
