# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0008_auto_20160819_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='competitors',
            field=models.ManyToManyField(blank=True, null=True, related_name='_authority_competitors_+', to='corrfeed.Authority'),
        ),
    ]
