# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0009_authority_competitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='no_of_feeds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
