# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0010_authority_no_of_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='no_of_rf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='no_of_urf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
