# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0011_auto_20160823_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='no_of_feeds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='authority',
            name='no_of_rf',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='authority',
            name='no_of_urf',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
