# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0013_auto_20160824_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='twitter_hashtag',
            new_name='twitter_handle',
        ),
    ]
