# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0016_auto_20160826_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='no_of_rf',
            new_name='resolved',
        ),
        migrations.RenameField(
            model_name='authority',
            old_name='no_of_urf',
            new_name='unresolved',
        ),
    ]
