# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corrfeed', '0018_auto_20160902_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='experienced',
            field=models.ManyToManyField(blank=True, related_name='experience', to=settings.AUTH_USER_MODEL),
        ),
    ]
