# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0019_feed_experienced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='experienced',
            new_name='users_experienced',
        ),
    ]
