# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 15:24
from __future__ import unicode_literals

import corrfeed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0020_auto_20160921_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='dp',
            field=models.ImageField(blank=True, upload_to=corrfeed.models.dp_path),
        ),
    ]
