# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrfeed', '0022_auto_20160922_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
